### ISSUE TITLE
ImportError: cannot import name 'update_sample_rate' from 'fairseq.data.audio.audio_utils'

### ISSUE THREAD

**Issue by BillSiriusLiu** [cwang621/zero-shot-st#1]
When i ran `bash egs/scripts/train-en2any-MT.sh` this error occurred.

> Traceback (most recent call last):
  File "/home/robot/.local/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/robot/home/robot/fairseq/fairseq_cli/train.py", line 541, in cli_main
    parser = options.get_training_parser()
  File "/home/robot/home/robot/fairseq/fairseq/options.py", line 38, in get_training_parser
    parser = get_parser("Trainer", default_task)
  File "/home/robot/home/robot/fairseq/fairseq/options.py", line 234, in get_parser
    utils.import_user_module(usr_args)
  File "/home/robot/home/robot/fairseq/fairseq/utils.py", line 491, in import_user_module
    importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/robot/home/robot/ZNLP/zero-shot-st/zero_shot_wave_to_text/__init__.py", line 1, in <module>
    from . import tasks, criterions, models, data, modules
  File "/home/robot/home/robot/ZNLP/zero-shot-st/zero_shot_wave_to_text/tasks/__init__.py", line 7, in <module>
    importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/robot/home/robot/ZNLP/zero-shot-st/zero_shot_wave_to_text/tasks/zero_shot_wave_to_text.py", line 20, in <module>
    from zero_shot_wave_to_text.data.wave_to_text_dataset import (
  File "/home/robot/home/robot/ZNLP/zero-shot-st/zero_shot_wave_to_text/data/__init__.py", line 7, in <module>
    importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/robot/home/robot/ZNLP/zero-shot-st/zero_shot_wave_to_text/data/wave_to_text_dataset.py", line 23, in <module>
    from fairseq.data.audio.audio_utils import get_fbank, update_sample_rate, _sox_convert, convert_to_mono
ImportError: cannot import name 'update_sample_rate' from 'fairseq.data.audio.audio_utils' (/home/robot/home/robot/fairseq/fairseq/data/audio/audio_utils.py)
egs/scripts/train-en2any-MT.sh: line 31: --optimizer: command not found
Traceback (most recent call last):
  File "/home/robot/.local/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/home/robot/home/robot/fairseq/fairseq_cli/generate.py", line 402, in cli_main
    parser = options.get_generation_parser()
  File "/home/robot/home/robot/fairseq/fairseq/options.py", line 49, in get_generation_parser
    parser = get_parser("Generation", default_task)
  File "/home/robot/home/robot/fairseq/fairseq/options.py", line 234, in get_parser
    utils.import_user_module(usr_args)
  File "/home/robot/home/robot/fairseq/fairseq/utils.py", line 491, in import_user_module
    importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/robot/home/robot/ZNLP/zero-shot-st/zero_shot_wave_to_text/__init__.py", line 1, in <module>
    from . import tasks, criterions, models, data, modules
  File "/home/robot/home/robot/ZNLP/zero-shot-st/zero_shot_wave_to_text/tasks/__init__.py", line 7, in <module>
    importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/robot/home/robot/ZNLP/zero-shot-st/zero_shot_wave_to_text/tasks/zero_shot_wave_to_text.py", line 20, in <module>
    from zero_shot_wave_to_text.data.wave_to_text_dataset import (
  File "/home/robot/home/robot/ZNLP/zero-shot-st/zero_shot_wave_to_text/data/__init__.py", line 7, in <module>
    importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/robot/home/robot/ZNLP/zero-shot-st/zero_shot_wave_to_text/data/wave_to_text_dataset.py", line 23, in <module>
    from fairseq.data.audio.audio_utils import get_fbank, update_sample_rate, _sox_convert, convert_to_mono
ImportError: cannot import name 'update_sample_rate' from 'fairseq.data.audio.audio_utils' (/home/robot/home/robot/fairseq/fairseq/data/audio/audio_utils.py)

> 
And then I checked the python file, which does not have the `update_sample_rate` function. Plus, it doesn't have `convert_to_mono` or `_sox_convert` either, but it does have `get_fbank`.

I thought this might have something to do with the fairseq version. I cloned the latest version of facebookresearch/fairseq from github, while in readme version `fairseq==1.0.0a0+741fd13` is required. However, I cannot find this version tag in facebookresearch/fairseq. Could you please provide the link of this `fairseq==1.0.0a0+741fd13` version? Or maybe this is not the cause?

**Comment by BillSiriusLiu** [comment]
My bad I see it in the releases.
